<a href="https://colab.research.google.com/github/Tiwari666/Data_Science_Python/blob/main/QA_IMP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1) Python code to get a list of all keys in a dictionary:**

In [6]:
d = {"Name": ["Alice", "Bob","Charlie"], "Age": [23, 25, 27], "Gender": ["Female", "Male", "Male"]}
d.keys()

dict_keys(['Name', 'Age', 'Gender'])

# **2) what is list compehension? Give me an example.**

List comprehension is a way to create a new list based on the values of an existing list.

There are two approaches to creat list:

A) Creating list using for loop under the Traditional approach

B) Creating List Using the list comprehension

# **A) Creating list using for loop under the Traditional approach**

In [7]:
numbers = [1,2,3,4,5]
squared_num = []
for num in numbers:
    squared_num.append(num**2)
print(squared_num)

[1, 4, 9, 16, 25]


# **B) Creating List Using the list comprehension**

In [8]:
numbers = [1,2,3,4,5]
square_num = [ num**2 for num in numbers]
print(squared_num)

[1, 4, 9, 16, 25]


# **AA) Creating list using for loop under the Traditional approach**

In [18]:
numbers = [1,2,3,4,5,6]
num_div_by_2 = []
for num in numbers:
    if num%2 ==0:
        num_div_by_2.append(num)
print(num_div_by_2)

[2, 4, 6]


# **BB) Creating List Using the list comprehension**

In [19]:
numbers = [1,2,3,4,5,6]
num_div_by_2 = [num for num in numbers if num%2 ==0]
print(num_div_by_2)

[2, 4, 6]


# **3) Map function:**

The map() function is a convenient way to apply a function to every item in an iterable without explicitly using a loop.

#Note On Function Exit:
In Python, a function exits when it reaches the end of its block of code, even without an explicit **return** statement or the **pass** keyword. If there is no explicit return statement, the function implicitly returns **None** when it reaches the end of its block.

In [28]:
def square(x):
    return x**2

numbers = [1,2,3,4,5]

square_numbers = map(square, numbers)

# we must convert the result to a list (optional, as map returns a map object).

square_numbers_list = list(square_numbers)

print(square_numbers_list)

[1, 4, 9, 16, 25]


# **ALTERNATIVE:Using a lambda function inside the map() function without explicitly defining a separate (square) function.**

In [27]:
numbers = [1,2,3,4,5]

square_num = map(lambda x : x**2, numbers)

square_num_list = list(square_num)

print(square_num_list)

[1, 4, 9, 16, 25]


# **4) Filters out the numbers divisible by 3 from a tuple using a lambda function and the filter() function:**

In [29]:
my_tuple = (1,2,3,4,5,6,7,8,9,10)

filtered_number = filter(lambda x : x %3 ==0, my_tuple)

filtered_tuple = tuple(filtered_number)

print(filtered_tuple)

(3, 6, 9)


# **5) Create a dataframe from a library:**

In [30]:
import pandas as pd
dict1 = {"Make": ["Toyota", "Honda", "Ford"], "Year": [2020, 2021, 2023], "Model": ["Camry", "Civic", "Fusion"]}
df = pd.DataFrame(dict1)
df

Make  Year   Model
0  Toyota  2020   Camry
1   Honda  2021   Civic
2    Ford  2023  Fusion

# **Difference between loc and iloc in python with example:**

In Python's Pandas library, loc and iloc are two important methods used for accessing data in a DataFrame.

# **loc:**

This method is used for selecting rows or columns primarily based on label index.

# **iloc**

This method is used for selecting rows or columns based  primarily on the index number.

In [35]:
d = {"a": [1,2,3,4], "b": [5,6,7,8], "c": [9,10,11,12]}
df = pd.DataFrame(d, index = ['r1', 'r2', 'r3','r4'])
df

a  b   c
r1  1  5   9
r2  2  6  10
r3  3  7  11
r4  4  8  12

In [40]:
df.loc['r1']

a    1
b    5
c    9
Name: r1, dtype: int64

In [42]:
df.iloc[0]

a    1
b    5
c    9
Name: r1, dtype: int64

In [46]:
df.loc['r1':'r2', 'b':]

b   c
r1  5   9
r2  6  10

In [58]:
df.iloc[0:2, 1:]

b   c
r1  5   9
r2  6  10

# **list.append():**
list.append(): This method is used to add a single element to the end of the list.

In [64]:
my_list = [1,2,3]
Another_list = [4,5,6]

print(my_list)
print("Shape of My list before append: ", len(my_list))

my_list.append(Another_list )

print(my_list)
print("Shape of My list after append: ", len(my_list))

[1, 2, 3]
Shape of My list before append:  3
[1, 2, 3, [4, 5, 6]]
Shape of My list after append:  4


# **list.extend():**
list.extend(): This method is used to extend a list by appending elements from an iterable (e.g., another list, tuple, or any other iterable) to the end of the list individually.


In [65]:
my_list = [1,2,3]
Another_list = [4,5,6]

print(my_list)
print("Shape of My list before extend: ", len(my_list))

my_list.extend(Another_list )

print(my_list)
print("Shape of My list after extend: ", len(my_list))

[1, 2, 3]
Shape of My list before extend:  3
[1, 2, 3, 4, 5, 6]
Shape of My list after extend:  6


# **Create a4X4 matrix and find the sum of all diagonal elements:**

In [87]:
import numpy as np
m = np.array([ [1,2,3,4],
     [5,6,7,8],
      [9,10,11,12],
      [13,14,15,16]])
print(m)

print('\nList of all diagonal elements: ',m.diagonal()) # numpy array is not callable

print("\nSum of all diagonal elements: ", m.diagonal().sum())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

List of all diagonal elements:  [ 1  6 11 16]

Sum of all diagonal elements:  34


# **Alternative:**

In [93]:
import numpy as np

# Create a 4x4 matrix using arange
matrix = np.arange(1, 17).reshape(4, 4)

# Calculate the sum of diagonal elements
sum_diagonal = np.trace(matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(matrix)

print("Matrix:")
print(matrix)

print("\nDiagonal elements:", diagonal_elements)
print("Sum of diagonal elements:", sum_diagonal)

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal elements: [ 1  6 11 16]
Sum of diagonal elements: 34


# **Find the mean, median, mode, standard deviation using Python's built-in functions and the statistics module:**

In [101]:
import statistics

numbers = [10,20,30, 40, 50]

# Calculate the average (mean)
Mean = sum(numbers)/len(numbers)

# Calculate the minimum
Minumum = min(numbers)


# Calculate the maximum
Maximum = max(numbers)
Maximum

st_dev = statistics.stdev(numbers)
st_dev

print(f"Mean: = {Mean}, Maximum:  {Maximum}, Standard Deviation:  {st_dev}")

Mean: = 30.0, Maximum:  50, Standard Deviation:  15.811388300841896


# **Group by and aggregate function**

In [104]:
import pandas as pd

# Create a sample DataFrame
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40, 50, 60]
}
df = pd.DataFrame(data)

# Group by 'Category' column and calculate the sum of 'Value' for each category
result = df.groupby('Category').agg({'Value': 'sum'})

print("Original DataFrame:")
print(df)
print("\nResult after grouping by 'Category' and calculating sum:")
print(result)

Original DataFrame:
  Category  Value
0        A     10
1        B     20
2        A     30
3        B     40
4        A     50
5        B     60

Result after grouping by 'Category' and calculating sum:
          Value
Category       
A            90
B           120
